### PR TITLE
ch(Integrate travis): Integrate Travis to readme

### PR DESCRIPTION
**Pull request by KarangwaEmmy**
**What does this PR do?**
Integrate Travis to the readme

**Description of Task to be completed?**
Have Travis integrated and all its services working
Easily sync your projects with Travis CI and it will be testing our code in minutes.

**How should this be manually tested?**
Clone this repo to your local machine and then run npm I,  to install all dependencies.
Run to see test if are passing.

**Any background context you want to provide?**
N/A

**What are the relevant pivotal tracker stories?**
#170764569

### CODE REVIEW

**Review by shaazk — COMMENTED** [review]
you have a conflicting file, resolve it

**Review by Skemc — COMMENTED** [review]
there is a conflicting file that needs to be solved

**Review by shaazk — APPROVED** [review]

**Review by KarangwaEmmy — COMMENTED** [review]
True

**Review by Skemc — APPROVED** [review]
Look good to me

**Review by shaazk — APPROVED** [review]

**Review by shaazk — APPROVED** [review]

**Review by ajimae — COMMENTED** [review]
LGTM

**Pull request merged**
