### PR TITLE
#170764593 remember user profile

### PR DESCRIPTION
**Pull request by niyodusengaclement**
#### What does this PR do?
Have auto-fill functionality
#### Description of Task to be completed?
When the user clicks on remember me, He won't provide his details at every travel request initiation. However, if you don't click on remember me checkbox, you will provide your details every time you request a trip.
#### How should this be manually tested?
Clone this repo, cd into the project directory and run the following commands:
 - npm install
 - npm start
open postman and send post request in this URL (localhost:5000/api/requests/one_way)
#### What are the relevant pivotal tracker stories?
[#170764593](https://www.pivotaltracker.com/story/show/170764593)

### CODE REVIEW

**Review by bihire — COMMENTED** [review]
try to fix that eslint error

**Comment by niyodusengaclement** [comment]
Resolved bro, check it out

**Review by ajimae — COMMENTED** [review]
LGTM!

**Review by ajimae — APPROVED** [review]

**Comment by ajimae** [comment]
This branch is no longer needed

**Pull request closed without merging**
