### PR TITLE
#170764580 login with google or facebook

### PR DESCRIPTION
**Pull request by niyodusengaclement**
#### What does this PR do?
Have login with Google or Facebook endpoint
#### Description of Task to be completed?
Allow user to login with Google
Allow user to login Facebook
Store user information in the database
#### How should this be manually tested?
clone this repo, open terminal, cd into project folder and run the following commands
  - npm install
  - npm start

Open the browser and request these link:
  - (localhost:5000/api/auth/google) for google sign in
  - (localhost:5000/api/auth/facebook) for facebook sign in

#### What are the relevant pivotal tracker stories?
#170764580
#### Questions:
To test user login with Facebook or Google is not easy as I thought it could but I will try to fix it

### CODE REVIEW

**Review by shaazk — CHANGES_REQUESTED** [review]
Hey Clement, can you fix all those hound violations and your tests are failing

**Review by Elvis-rugamba — COMMENTED** [review]
Fix your tests

**Comment by niyodusengaclement** [comment]
Hound violation is caused by its configurations are different from eslint
rules, because on my local machine no violation of those rules
Tests are failing because of ENV variables are not set in Travis but I've
sent messages on channel they going to do it

**Review by ajimae — COMMENTED** [review]
Have to close this branch due to excessive commit on it.

**Pull request closed without merging**
